### ISSUE TITLE
Unexpected token '?' on npm run dev

### ISSUE THREAD

**Issue by iSubhamMani** [AI-RES/WebClient-OpenEdu#10]
I'm having an issue on setting up the project, when I'm trying to run the dev server it throws the below error. Any fix around this issue ?

Steps to reproduce:
1. npm install
2. npm run dev

![Screenshot from 2023-12-30 11-37-52](https://github.com/AI-RES/WebClient-OpenEdu/assets/134488182/142ea63d-0e8d-497b-8cc5-cba331eeb63a)

**Comment by Himasnhu-AT** [comment]
Hi @iSubhamMani , the issues seems to be around the node version used as node 14 and above allows for the use of nullish coalescing operator

**Comment by Himasnhu-AT** [comment]
Try updating to latest node version available

**Comment by iSubhamMani** [comment]
Thanks a lot!
