### ISSUE TITLE
Improve UI of public profile

### ISSUE THREAD

**Issue by Himasnhu-AT** [AI-RES/WebClient-OpenEdu#5]
Enhance the User Interface for the Public Profile

Revamp the layout and aesthetics of the Public Profile UI to achieve a more visually appealing design.

[Access Public Profile Page Here](https://web-client-ai-res.vercel.app/p/1)

![Public Profile Screenshot](https://github.com/AI-RES/WebClient/assets/117301124/3c99136d-9e29-4ee2-a8a1-230dded0583a)

Objective:
- Redesign the Public Profile UI to improve overall user experience.
- Enhance the layout for better visual harmony.
- Optimize the aesthetics to create an attractive and user-friendly interface.

**Comment by iSubhamMani** [comment]
Hi @Himasnhu-AT I would like to work on this issue. Can we connect somewhere to discuss the work further ?

**Comment by Himasnhu-AT** [comment]
Sure, we can connect over discord:
My username: himanshu2005
Kindly ping me if you need any help.
